"""项目常量定义"""

PARTITION_STYLE_GPT = "GPT"
PARTITION_STYLE_MBR = "MBR"
PARTITION_STYLE_RAW = "RAW"

FILE_SYSTEM_FAT32 = "FAT32"
FILE_SYSTEM_NTFS = "NTFS"

VOLUME_LABEL_EFI = "EFI"
VOLUME_LABEL_WINDOWS = "Windows"
VOLUME_LABEL_DATA1 = "Data1"
VOLUME_LABEL_DATA2 = "Data2"

EFI_PARTITION_GUID = "{c12a7328-f81f-11d2-ba4b-00a0c93ec93b}"
MSR_PARTITION_GUID = "{e3c9e316-0b5c-4db8-817d-f92df00215ae}"


class ErrorCode:
    """统一错误码定义"""
    SUCCESS = 0
    PREFLIGHT_FAILED = 1
    INITIALIZATION_FAILED = 2
    PARTITION_FAILED = 3
    GHOST_FAILED = 4
    COPY_FAILED = 5
    BOOT_FAILED = 6
    VALIDATION_FAILED = 7
    CONFIG_ERROR = 8
    DISK_PROTECTED = 9
    IDENTITY_MISMATCH = 10
    PATH_TRAVERSAL = 11
